# -*- coding: utf-8 -*-
"""data_augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gm-40wrGaZNBP9g0YzJ8O_Peu5s7590K
"""

# data augmentation

# loading the image using keras 
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array

datagenerate  = ImageDataGenerator(
    rotation_range=50, 
    width_shift_range=0.2, 
    height_shift_range=0.2, 
    shear_range=0.2, 
    zoom_range=0.2, 
    horizontal_flip =True,
    fill_mode='nearest'
    )

import tensorflow as tf

image = tf.keras.preprocessing.image.load_img('/content/dog_1.jpeg')



x = img_to_array(image) 
x = x.reshape((1,) + x.shape) 

# the flow command generated batches of randomly transformed images and saves the results to preview dir

i = 0
for batch in datagenerate.flow(x, batch_size = 1, 
                               save_to_dir = 'preview',
                               save_prefix = 'dog',
                               save_format = 'png'):
    i +=1
    if i>20:
        break